# Generated by Django 4.0.3 on 2022-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('ST', 'Short Term'), ('LT', 'Long Term')], default='ST', max_length=50),
        ),
    ]
