# Generated by Django 4.0.3 on 2022-03-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_goal_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='course_id',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='project_id',
            new_name='project',
        ),
    ]
