# Generated by Django 4.0.3 on 2022-03-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_rename_course_id_goal_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='courses',
            new_name='course',
        ),
    ]
