# Generated by Django 4.0.3 on 2022-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_rename_courses_goal_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
