# Generated by Django 4.0.3 on 2022-03-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_goal_description_alter_goal_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
