# Generated by Django 4.0.3 on 2022-04-21 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SP', 'Single Payment'), ('MS', 'Month Subscription'), ('AS', 'Annual Subscription'), ('PP', 'Payment Plan')], default='SP', max_length=2)),
                ('is_one_time_pay', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('purchase_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='courses.purchasetype')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('help_me_to', models.TextField(blank=True, max_length=3000, null=True)),
                ('be_great', models.TextField(blank=True, max_length=3000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.company')),
                ('projects', models.ManyToManyField(related_name='projects', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.TextField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('why_not_now', models.TextField(blank=True, max_length=3000, null=True)),
                ('notes', models.TextField(blank=True, max_length=3000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.company')),
            ],
        ),
        migrations.CreateModel(
            name='StudyTimetable',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.course')),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_on', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
        ),
    ]
