# Generated by Django 4.0.3 on 2022-03-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
