# Generated by Django 4.0.3 on 2022-04-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_course'),
        ('courses', '0007_studytimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SP', 'Single Payment'), ('MS', 'Month Subscription'), ('AS', 'Annual Subscription'), ('PP', 'Payment Plan')], default='SP', max_length=2)),
                ('is_one_time_pay', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studytimetable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studytimetable',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='studytimetable',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='studytimetable',
            name='date_logged',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studytimetable',
            name='time_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studytimetable',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CourseWishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.TextField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('why_not_now', models.TextField(blank=True, max_length=3000, null=True)),
                ('notes', models.TextField(blank=True, max_length=3000, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.company')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.company'),
        ),
        migrations.AlterField(
            model_name='course',
            name='purchase_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='courses.purchasetype'),
        ),
    ]
