# Generated by Django 4.0.3 on 2022-04-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_company_purchasetype_remove_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursewishlist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.company'),
        ),
    ]
