# Generated by Django 4.0.3 on 2022-03-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='course_id',
            new_name='course',
        ),
    ]
