# Generated by Django 4.0.3 on 2022-03-25 14:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_alter_course_user'),
        ('projects', '0007_projecttimetable_milestones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Milestones',
            new_name='Milestone',
        ),
    ]
