# Generated by Django 4.0.3 on 2022-03-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_milestones_milestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='course',
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
