# Generated by Django 4.0.3 on 2022-03-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_milestone_course_milestone_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='description',
        ),
    ]
