# Generated by Django 4.0.3 on 2022-03-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_milestone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttimetable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
