# Generated by Django 4.0.3 on 2022-03-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_projecttimetable_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='course',
        ),
    ]
